--declaração de variavéis
DECLARE @MATRICULA VARCHAR(5),
        @NOME VARCHAR(100),
        @PERCENTUAL FLOAT,
        @DATA DATE,
        @FERIAS BIT,
        @BAIRRO VARCHAR(100);

--inserção dos dados nas variaveis
SET @MATRICULA = '00240';
SET @NOME = 'João Silva';
SET @PERCENTUAL = 0.09;
SET @DATA = GETDATE();
SET @FERIAS = 0;
SET @BAIRRO = 'Jardim dos Frutas';

--mostando os dados na tela
SELECT @MATRICULA AS MATRICULA, @NOME AS NOME, @PERCENTUAL AS PERCENTUAL, @DATA AS DATA_INSERCAO;

SELECT * 
FROM [TABELA DE VENDEDORES];

INSERT INTO [TABELA DE VENDEDORES]
    ([MATRICULA], [NOME], [PERCENTUAL COMISSÃO], [DATA ADMISSÃO], [DE FERIAS], [BAIRRO])
VALUES
    (@MATRICULA, @NOME, @PERCENTUAL, @DATA, @FERIAS, @BAIRRO)

DELETE FROM [TABELA DE VENDEDORES] WHERE MATRICULA = '00240';

DECLARE @CPF_CLIENTE VARCHAR(11),
        @NOME_CLIENTE VARCHAR(100),
        @DATA_NASCIMENTO DATE,
        @IDADE INT;

SET @CPF_CLIENTE = '19290992743';

SELECT @NOME_CLIENTE = NOME, @DATA_NASCIMENTO = [DATA DE NASCIMENTO], @IDADE = IDADE
FROM [TABELA DE CLIENTES]
WHERE CPF = @CPF_CLIENTE;

PRINT @NOME_CLIENTE;
PRINT @DATA_NASCIMENTO;
PRINT @IDADE;

DECLARE @NUMNOTAS INT;

SELECT @NUMNOTAS = COUNT(*)
FROM [NOTAS FISCAIS]
WHERE DATA = '2017/01/01';