SELECT COUNT(*)
FROM TABELA_DE_CLIENTES;

SELECT COUNT(*)
FROM TABELA_DE_PRODUTOS;

SELECT COUNT(*)
FROM TABELA_DE_VENDEDORES;

SELECT COUNT(*)
FROM NOTAS_FISCAIS;

SELECT COUNT(*)
FROM ITENS_NOTAS_FISCAIS;

SELECT *
FROM TABELA_DE_CLIENTES
WHERE NOME LIKE '%Silva%';

SELECT DISTINCT SABOR
FROM TABELA_DE_PRODUTOS;

SELECT  DISTINCT TOP 5 SABOR
FROM TABELA_DE_PRODUTOS;

SELECT TOP 10 *
FROM NOTAS_FISCAIS
WHERE DATA_VENDA = '01/10/2017';

SELECT *
FROM NOTAS_FISCAIS
ORDER BY MATRICULA ASC;

SELECT *
FROM ITENS_NOTAS_FISCAIS
WHERE CODIGO_DO_PRODUTO = '1101035'
ORDER BY QUANTIDADE DESC;

SELECT *
FROM TABELA_DE_PRODUTOS;

SELECT *
FROM ITENS_NOTAS_FISCAIS;

SELECT CODIGO_DO_PRODUTO, SUM(QUANTIDADE) AS QTD
FROM ITENS_NOTAS_FISCAIS
GROUP BY CODIGO_DO_PRODUTO
ORDER BY QTD DESC;

SELECT CODIGO_DO_PRODUTO, SUM(QUANTIDADE) AS QTD
FROM ITENS_NOTAS_FISCAIS
GROUP BY CODIGO_DO_PRODUTO
HAVING SUM(QUANTIDADE) > 394000
ORDER BY QTD DESC;

SELECT NOME, CPF, 
CASE
	WHEN LIMITE_DE_CREDITO >= 150000 THEN 'Cliente grande'
	WHEN LIMITE_DE_CREDITO BETWEEN 110000 AND 150000 THEN 'Cliente médio'
	ELSE 'Cliente pequeno'
END AS CLASSIFICAÇÃO
FROM TABELA_DE_CLIENTES;

SELECT INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO, SUM(INF.QUANTIDADE) AS QUANTIDADE 
FROM ITENS_NOTAS_FISCAIS INF
INNER JOIN TABELA_DE_PRODUTOS TP
ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
GROUP BY INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO
HAVING SUM(INF.QUANTIDADE) > 394000 
ORDER BY SUM(INF.QUANTIDADE) DESC;

SELECT INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO, SUM(INF.QUANTIDADE) AS QUANTIDADE 
FROM ITENS_NOTAS_FISCAIS INF
INNER JOIN TABELA_DE_PRODUTOS TP
ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
GROUP BY INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO
HAVING SUM(INF.QUANTIDADE) > 394000 
ORDER BY SUM(INF.QUANTIDADE) DESC;

SELECT DISTINCT SABOR 
FROM TABELA_DE_PRODUTOS 
WHERE CODIGO_DO_PRODUTO IN (
	SELECT INF.CODIGO_DO_PRODUTO 
	FROM ITENS_NOTAS_FISCAIS  INF
	INNER JOIN TABELA_DE_PRODUTOS TP 
	ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
	GROUP BY INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO HAVING SUM(INF.QUANTIDADE) > 394000 );

SELECT SC.CODIGO_DO_PRODUTO, SC.NOME_DO_PRODUTO, SC.QUANTIDADE_TOTAL
FROM
	(	SELECT INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO, SUM(INF.QUANTIDADE) AS QUANTIDADE_TOTAL 
		FROM ITENS_NOTAS_FISCAIS  INF
		INNER JOIN TABELA_DE_PRODUTOS TP 
		ON INF.CODIGO_DO_PRODUTO = TP.CODIGO_DO_PRODUTO
		GROUP BY INF.CODIGO_DO_PRODUTO, TP.NOME_DO_PRODUTO
	) SC
WHERE SC.QUANTIDADE_TOTAL > 394000 
ORDER BY SC.QUANTIDADE_TOTAL DESC;

CREATE VIEW MEDIA_EMBALAGENS AS 
	SELECT EMBALAGEM, AVG(PRECO_DE_LISTA) AS PRECO_MEDIA
	FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM;

SELECT * FROM MEDIA_EMBALAGENS;

SELECT NOME, CHARINDEX(' ', NOME, 1) FROM TABELA_DE_CLIENTES;

SELECT NOME, SUBSTRING(NOME, 1, CHARINDEX(' ', NOME, 1)) FROM TABELA_DE_CLIENTES;


SELECT CONCAT('O cliente ', NOME, ' nasceu em ', DATENAME(day, DATA_DE_NASCIMENTO), ' de ', DATENAME(month, DATA_DE_NASCIMENTO), ' no ano de ', DATENAME(year, DATA_DE_NASCIMENTO)) AS NASCIMENTO
FROM TABELA_DE_CLIENTES;

SELECT CONCAT('O cliente ', TC.NOME, 'comprou R$', TRIM(STR(SUM(INF.QUANTIDADE * INF.PRECO) ,10,2)), ' no ano de 2016') AS VALOR
FROM  NOTAS_FISCAIS NF
INNER JOIN ITENS_NOTAS_FISCAIS INF ON INF.NUMERO = NF.NUMERO
INNER JOIN TABELA_DE_CLIENTES TC ON TC.CPF = NF.CPF
WHERE YEAR(NF.DATA_VENDA) = '2016'
GROUP BY TC.NOME, YEAR(NF.DATA_VENDA);

SELECT TC.NOME, CONCAT('O cliente ', TC.NOME, ' comprou R$ ',
TRIM(STR(SUM(IT.QUANTIDADE * IT.PRECO) ,10,2)), ' no ano de ', YEAR(NF.DATA_VENDA), '.') AS VALOR
FROM NOTAS_FISCAIS AS NF
INNER JOIN ITENS_NOTAS_FISCAIS AS IT ON NF.NUMERO = IT.NUMERO
INNER JOIN TABELA_DE_CLIENTES AS TC ON NF.CPF = TC.CPF
WHERE YEAR(NF.DATA_VENDA) = '2016'
GROUP BY TC.NOME, YEAR(NF.DATA_VENDA);